language: cpp
sudo: required
dist: trusty
compiler:
  - gcc

before_install:
  - sudo apt-get update

install:
 - sudo apt-get install build-essential
 - sudo apt-get install cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
 - sudo apt-get install python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev
 - git clone https://github.com/opencv/opencv.git opencv
 - cd opencv
 - mkdir build && cd build
 - cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local ..
 - make -j7
 - sudo make install
 - cd ../../

script:
 - mkdir build && cd build
 - cmake ..
 - make